// src/app/rx-example/rx-example-react.component.tsx
import * as React from 'react';
import {timer} from 'rxjs/observable/timer';

export interface RxProps {
  transpiler: string;
  framework: string;
  compiler: string;
}

// 'RxProps' describes the shape of props.
// State is never set so we use the '{}' type.
export class RxExampleReactComponent extends React.Component<RxProps, {}> {

  componentDidMount() {
    timer(1000, 250).subscribe((value: number) => {
      this.setState({reactMilliseconds: value});
    });
  }

  constructor(props: RxProps) {
    super(props, {});

    this.state = { seconds: 0, reactSeconds: 0 };
  }

  render() {
    return <div>
      <h1>This is the {this.props.transpiler} and {this.props.framework} component</h1>
      <h2>Angular parent timer: { this.state['seconds'] }</h2>
      <h2>React component timer: { this.state['reactMilliseconds'] }</h2>
    </div>;
  }
}

// src/app/rx-example/rx-example.component.ts
import { Component, OnInit } from '@angular/core';
import {RxExampleReactComponent} from './rx-example-react.component';
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import {timer} from 'rxjs/observable/timer';

@Component({
  selector: 'app-rx-example',
  templateUrl: './rx-example.component.html',
  styleUrls: ['./rx-example.component.css']
})
export class RxExampleComponent implements OnInit {

  rxExampleReactComponent: RxExampleReactComponent;

  ngOnInit() {
    const reactProps = {
      transpiler: 'Angular 5',
      framework: 'React 16',
      compiler: 'none'
    };

    const source = timer(1000, 1000).subscribe((value: number) => {
      this.rxExampleReactComponent.setState({seconds: value});
    });

    this.rxExampleReactComponent = ReactDOM.render(
      React.createElement(RxExampleReactComponent, reactProps),
      document.getElementById('rxDiv')
    );
  }

}

<p>
  rx-example works!
</p>
